data_type: image
repo_path: .

recreate_dataset: true

batch_size: 10
test_batch_size: 100
lr: 0.01
momentum: 0.9
decay: 0.0005
total_rounds: 199
save_on_rounds: [50,100,150,200]
optimizer: SGD
multi_gpu: false
gpu: 0
non_iid_alpha: 0.9

save_model: true

# parameters for Federated Learning
aggregation_type: averaging
### averaging or median
number_of_total_participants: 100
no_models: 10
retrain_no_times: 5
eta: 1

diff_privacy: false
s_norm: 15
sigma: 0.01

log: True
tb: True
random: False